get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

####################################################################################

set (XNNPACK_FOUND 1)
#set (XNNPACK_USE_FILE    "${CMAKE_CURRENT_LIST_DIR}/UseEigen3.cmake")

set (XNNPACK_DEFINITIONS  "")
set (XNNPACK_INCLUDE_DIR  "${PACKAGE_PREFIX_DIR}/include/")
set (XNNPACK_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include/")
set (XNNPACK_LIBRARIES    "${PACKAGE_PREFIX_DIR}/lib/libXNNPACK${CMAKE_STATIC_LIBRARY_SUFFIX}")
set (XNNPACK_ROOT_DIR     "${PACKAGE_PREFIX_DIR}")

add_library(XNNPACK STATIC IMPORTED)

set_target_properties(XNNPACK PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${XNNPACK_INCLUDE_DIR}"
  IMPORTED_LOCATION "${XNNPACK_LIBRARIES}"
  IMPORTED_LINK_INTERFACE_LIBRARIES "${PACKAGE_PREFIX_DIR}/lib/libpthreadpool.a"
)
